export const SIGNUP_EXIT = "SIGNUP_EXIT";
export const LOGIN_EXIT = "LOGIN_EXIT";
export const ERROR = "ERROR";
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const OBTENER_USUARIO_ERROR = "OBTENER_USUARIO_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
